export const PROFILE_PATH= '/ca-nhan'
export const PROFILE_PROJECT_PATH= '/ca-nhan/du-an'
export const PROFILE_COURSE_PATH= '/ca-nhan/khoa-hoc'
export const PROFILE_COIN_PATH= '/ca-nhan/coin'
export const PROFILE_PAYMENT_PATH= '/ca-nhan/lich-su-thanh-toan'
export const COURSE_DETAIL = '/khoa-hoc/:slug'
